site_name: TIL
theme:
    name: material
repo_name: stickperson/TIL
repo_url: https://github.com/stickperson/TIL
nav:
  - TIL: index.md
  - Django:
    - Adding non-model fields when using ModelAdmin: 'django/adding-non-model-fields-using-modeladmin.md'
    - Editing related objects in the admin: 'django/editing-related-objects-in-admin.md'
  - OpenWRT:
    - Custom DNS: 'openwrt/custom_dns/custom_dns.md'
  - Postgres:
    - Explicit JOINs and Genetic Query Optimization: 'postgres/explicit_joins_and_geqo_threshold.md'
    - Slow Local Postgres Connection: 'postgres/slow_local_postgres_connection.md'
  - Python:
    - Auto-reload in iPython: 'python/auto-reload-ipython.md'
  - Raspberry Pi:
    - Headless Setup: 'raspberry_pi/headless_setup.md'
  - Unix:
    - Exit Frozen SSH: 'unix/exit_frozen_ssh.md'
  - Vim:
    - Format JSON: 'vim/format_json.md'
